---
title: "Aim 2 - Case-time series"
author: "Shreya Patel"
format: html
editor: visual
---

```{r}
#| echo: false
#| warning: false
 #| message: false # Removes messages

library(lubridate)
library(tidyverse)
library(glue)
library(gt)
library(gnm) 
library(dlnm)
library(splines)
library(mvmeta)
library(survival)

source('Y:/patels/Code/edvisits2.R')


```

```{r}
#| echo: false
#| message: false # Removes messages

edpregpp$case=1
edpregpp$dateonly=edpregpp$claim_date
load('Y:/patels/Data/temp1619.Rdata')
edpregpp.temp = edpregpp  %>%
  left_join(daily.temp.all, by='dateonly')


counts <- edpregpp.temp %>%
  #filter(preg==1) %>%
  group_by(dateonly) %>%
  summarise(
    case = sum(case, na.rm = TRUE),
    tmax   = mean(temp.max, na.rm = TRUE),
    tmean   = mean(temp.mean, na.rm = TRUE),   
    tmin   = mean(temp.min, na.rm = TRUE),   
    .groups = "drop"
  )

holiday_dates <- as.Date(c(
  # Memorial Day (last Monday of May)
  "2016-05-30", "2017-05-29", "2018-05-28", "2019-05-27",
  # Independence Day
  "2016-07-04", "2017-07-04", "2018-07-04", "2019-07-04",
  # Labor Day (first Monday of September)
  "2016-09-05", "2017-09-04", "2018-09-03", "2019-09-02"
))

counts <- counts %>% 
  mutate(holiday = if_else(dateonly %in% holiday_dates, 1, 0))



counts_ct <- counts %>%
  mutate(strata = factor(glue("{year(dateonly)}:{month(dateonly)}:{wday(dateonly)}")))



# FUNCTION TO COMPUTE THE Q-AIC IN QUASI-POISSON MODELS
fqaic <- function(model) {
  loglik <- sum(dpois(model$y,model$fitted.values,log=TRUE))
  phi <- summary(model)$dispersion
  qaic <- -2*loglik + 2*summary(model)$df[3]*phi
  return(qaic)
}



run_cts <- function(data=counts,
                     temp=counts$tmean,
                     knots=c(0.33,0.66)
) {
  
  perc <- quantile(temp,probs=c(0.90,0.95, 0.975, 0.99))
  exp_knots <- quantile(temp,probs=knots, na.rm = TRUE)
  
  #cross basis 
  cb <- crossbasis(temp,
                   lag=7,
                   argvar=list(fun = "ns", 
                               knots = exp_knots),
                   arglag = list(fun = "ns", 
                                 knots = logknots(7, 2)))
  
  

model <- gnm(case ~ cb + holiday, eliminate = (strata),  family = quasipoisson, data = data)


#cross prediction is making predictions based on the output from the model 
#RR at percentiles in ref to centering value (20C)
cen=median(temp)
cp_overall <- crosspred(cb, model,
                        cen = cen,
                        at = seq(min(temp, na.rm = TRUE),
                                 max(temp, na.rm = TRUE),
                                 length = 100))

cp_perc <- crosspred(cb, model,
                     cen = cen,
                     at = perc,
                  2)


#png(filename=plot_name, width = 1200, height = 800, res = 150) 
par(mfrow = c(1, 2), mar = c(5, 4, 4, 2) + 0.1)

## Exposure-response curve
plot(cp_overall, "overall",
     col = 1,
     ylab = "RR",
     xlab = "Average Temperature (°F)",
     axes = TRUE,
     lwd = 1.5,
     log = "y",
     main = "Exposure-Response: Extreme Heat and ED Visits", cex.main = 0.8)
abline(v = perc, col = "red", lty = 2)
mtext(paste0("Ref = ", round(cen, 1), "°F"), cex = 0.6)

## Lag-response at 90th percentile
plot(cp_perc, "slices",
     var = as.numeric(perc["99%"]),
     col = 1,
     ylab = "OR",
     xlab = "Lag (days)",
     lwd = 1.5,
     main = paste0("Lag-Response (", round(perc["99%"], 1), "°F)"), cex.main = 0.8)
mtext(paste0("Ref = ", round(cen, 1), "°F"), cex = 0.6)


# Save results as a dataframe
cumulativeRR <- data.frame(
  Knots = paste0("(", paste(round(knots, 2), collapse = ", "), ")"),
  Percentile = names(perc),
  Temperature = round(as.numeric(perc),2),
  AIC = fqaic(model),
  RR = round(cp_perc$allRRfit, 2),
  LowerCI = round(cp_perc$allRRlow, 2),
  UpperCI = round(cp_perc$allRRhigh, 2)
)

return(cumulativeRR)
}



```

## All cause antepartum and postpartum

```{r}
#| message: false # Removes messages
#| echo: false

run_cts(data=counts_ct,
         temp=counts_ct$tmean,
         knots=c(0.33,0.66)) 

run_cts(data=counts_ct,
         temp=counts_ct$tmean,
         knots=c(0.50,0.90)) 

run_cts(data=counts_ct,
         temp=counts_ct$tmean,
         knots=c(0.10,0.75)) 


run_cts(data=counts_ct,
        temp=counts_ct$tmean,
        knots=c(0.25,0.50,0.75)) 

```

#### knots at (0.10,0.75) has the lowest AIC

# Antepartum

```{r}
#| message: false # Removes messages
#| echo: false

counts_preg <- edpregpp.temp %>%
  filter(preg==1) %>%
  group_by(dateonly) %>%
  summarise(
    case = sum(case, na.rm = TRUE),
    tmax   = mean(temp.max, na.rm = TRUE),
    tmean   = mean(temp.mean, na.rm = TRUE),   
    tmin   = mean(temp.min, na.rm = TRUE),   
    .groups = "drop"
  )

counts_preg <- counts_preg %>% 
  mutate(holiday = if_else(dateonly %in% holiday_dates, 1, 0))


counts_ct_preg <- counts_preg %>%
  mutate(strata = factor(glue("{year(dateonly)}:{month(dateonly)}:{wday(dateonly)}")))

run_cts(data=counts_ct_preg,
         temp=counts_ct_preg$tmean,
         knots=c(0.33,0.66)) 

run_cts(data=counts_ct_preg,
         temp=counts_ct_preg$tmean,
         knots=c(0.50,0.90)) 

run_cts(data=counts_ct_preg,
         temp=counts_ct_preg$tmean,
         knots=c(0.10,0.75)) 

run_cts(data=counts_ct_preg,
        temp=counts_ct_preg$tmean,
        knots=c(0.25,0.50,0.75)) 

```

#### knots at (0.10, 0.75) has the lowest AIC

# Postpartum

```{r}
#| message: false # Removes messages
#| echo: false

counts_pp <- edpregpp.temp %>%
  filter(postpartum==1) %>%
  group_by(dateonly) %>%
  summarise(
    case = sum(case, na.rm = TRUE),
    tmax   = mean(temp.max, na.rm = TRUE),
    tmean   = mean(temp.mean, na.rm = TRUE),   
    tmin   = mean(temp.min, na.rm = TRUE),   
    .groups = "drop"
  )

counts_pp <- counts_pp %>% 
  mutate(holiday = if_else(dateonly %in% holiday_dates, 1, 0))


counts_ct_pp <- counts_pp %>%
  mutate(strata = factor(glue("{year(dateonly)}:{month(dateonly)}:{wday(dateonly)}")))


run_cts(data=counts_ct_pp,
         temp=counts_ct_pp$tmean,
         knots=c(0.33,0.66)) 

run_cts(data=counts_ct_pp,
         temp=counts_ct_pp$tmean,
         knots=c(0.50,0.90)) 

run_cts(data=counts_ct_pp,
         temp=counts_ct_pp$tmean,
         knots=c(0.10,0.75)) 

run_cts(data=counts_ct_pp,
        temp=counts_ct_pp$tmean,
        knots=c(0.25,0.50,0.75)) 

```

#### knots at (0.50,0.90) has the lowest AIC

# Mental health visits

```{r}
#| message: false # Removes messages

mental$dateonly=mental$claim_date
#load('Y:/patels/Data/temp1619.Rdata')
mental.temp = mental  %>%
 left_join(daily.temp.all, by='dateonly')


counts_mental <- mental.temp %>%
  #filter(preg==1) %>%
  group_by(dateonly) %>%
  summarise(
    case = sum(mental, na.rm = TRUE),
    tmax   = mean(temp.max, na.rm = TRUE),
    tmean   = mean(temp.mean, na.rm = TRUE),   
    tmin   = mean(temp.min, na.rm = TRUE),   
    .groups = "drop"
  )

counts_mental <- counts_mental %>% 
  mutate(holiday = if_else(dateonly %in% holiday_dates, 1, 0))

counts_mental <- counts_mental %>%
  mutate(strata = factor(glue("{year(dateonly)}:{month(dateonly)}:{wday(dateonly)}")))


run_cts(data=counts_mental,
         temp=counts_mental$tmean,
         knots=c(0.33,0.66)) 

run_cts(data=counts_mental,
         temp=counts_mental$tmean,
         knots=c(0.50,0.90)) 

run_cts(data=counts_mental,
         temp=counts_mental$tmean,
         knots=c(0.10,0.75)) 

run_cts(data=counts_mental,
        temp=counts_mental$tmean,
        knots=c(0.25,0.50,0.75)) 

```

#### knots at (0.33,0.66) has the lowest AIC

# Pregnancy related visits

```{r}
#| message: false
#| echo: false

preg$dateonly=preg$claim_date
#load('Y:/patels/Data/temp1619.Rdata')
preg.temp = preg  %>%
 left_join(daily.temp.all, by='dateonly')


counts_pregel <- preg.temp %>%
  #filter(preg==1) %>%
  group_by(dateonly) %>%
  summarise(
    case = sum(pregc, na.rm = TRUE),
    tmax   = mean(temp.max, na.rm = TRUE),
    tmean   = mean(temp.mean, na.rm = TRUE),   
    tmin   = mean(temp.min, na.rm = TRUE),   
    .groups = "drop"
  )

counts_pregel <- counts_pregel %>% 
  mutate(holiday = if_else(dateonly %in% holiday_dates, 1, 0))

counts_pregel <- counts_pregel %>%
  mutate(strata = factor(glue("{year(dateonly)}:{month(dateonly)}:{wday(dateonly)}")))


run_cts(data=counts_pregel,
         temp=counts_pregel$tmean,
         knots=c(0.33,0.66)) 

run_cts(data=counts_pregel,
         temp=counts_pregel$tmean,
         knots=c(0.50,0.90)) 

run_cts(data=counts_pregel,
         temp=counts_pregel$tmean,
         knots=c(0.10,0.75)) 

run_cts(data=counts_pregel,
        temp=counts_pregel$tmean,
        knots=c(0.25,0.50,0.75)) 


```
#### knots at (0.10,0.75) has the lowest AIC

# injury

```{r}
#| message: false
#| echo: false

injury$dateonly=injury$claim_date
#load('Y:/patels/Data/temp1619.Rdata')
injury.temp = injury  %>%
 left_join(daily.temp.all, by='dateonly')


counts_injury <- injury.temp %>%
  #filter(preg==1) %>%
  group_by(dateonly) %>%
  summarise(
    case = sum(injury, na.rm = TRUE),
    tmax   = mean(temp.max, na.rm = TRUE),
    tmean   = mean(temp.mean, na.rm = TRUE),   
    tmin   = mean(temp.min, na.rm = TRUE),   
    .groups = "drop"
  )

counts_injury<- counts_injury %>% 
  mutate(holiday = if_else(dateonly %in% holiday_dates, 1, 0))

counts_injury_cts <- counts_injury %>%
  mutate(strata = factor(glue("{year(dateonly)}:{month(dateonly)}:{wday(dateonly)}")))

run_cts(data=counts_injury_cts,
         temp=counts_injury_cts$tmean,
         knots=c(0.33,0.66)) 

run_cts(data=counts_injury_cts,
         temp=counts_injury_cts$tmean,
         knots=c(0.50,0.90)) 

run_cts(data=counts_injury_cts,
         temp=counts_injury_cts$tmean,
         knots=c(0.10,0.75)) 

run_cts(data=counts_injury_cts,
        temp=counts_injury_cts$tmean,
        knots=c(0.25,0.50,0.75)) 

```

#### knots at (0.50,0.90) has the lowest AIC

# Respiratory

```{r}
#| message: false
#| echo: false

resp$dateonly=resp$claim_date
#load('Y:/patels/Data/temp1619.Rdata')
resp.temp = resp  %>%
 left_join(daily.temp.all, by='dateonly')


counts_resp <- resp.temp %>%
  #filter(preg==1) %>%
  group_by(dateonly) %>%
  summarise(
    case = sum(resp, na.rm = TRUE),
    tmax   = mean(temp.max, na.rm = TRUE),
    tmean   = mean(temp.mean, na.rm = TRUE),   
    tmin   = mean(temp.min, na.rm = TRUE),   
    .groups = "drop"
  )

holiday_dates <- as.Date(c(
  # Memorial Day (last Monday of May)
  "2016-05-30", "2017-05-29", "2018-05-28", "2019-05-27",
  # Independence Day
  "2016-07-04", "2017-07-04", "2018-07-04", "2019-07-04",
  # Labor Day (first Monday of September)
  "2016-09-05", "2017-09-04", "2018-09-03", "2019-09-02"
))

counts_resp<- counts_resp%>% 
  mutate(holiday = if_else(dateonly %in% holiday_dates, 1, 0))

counts_resp_cts <- counts_resp %>%
  mutate(strata = factor(glue("{year(dateonly)}:{month(dateonly)}:{wday(dateonly)}")))


run_cts(data=counts_resp_cts,
         temp=counts_resp_cts$tmean,
         knots=c(0.33,0.66)) 

run_cts(data=counts_resp_cts,
         temp=counts_resp_cts$tmean,
         knots=c(0.50,0.90)) 

run_cts(data=counts_resp_cts,
         temp=counts_resp_cts$tmean,
         knots=c(0.10,0.75)) 

run_cts(data=counts_resp_cts,
        temp=counts_resp_cts$tmean,
        knots=c(0.25,0.50,0.75)) 

```

#### knots at (0.50,0.90) has the lowest AIC


# Genitourinary

```{r}
#| message: false
#| echo: false


genit$dateonly=genit$claim_date
#load('Y:/patels/Data/temp1619.Rdata')
genit.temp = genit  %>%
 left_join(daily.temp.all, by='dateonly')


counts_genit <- genit.temp %>%
  group_by(dateonly) %>%
  summarise(
    case = sum(genit, na.rm = TRUE),
    tmax   = mean(temp.max, na.rm = TRUE),
    tmean   = mean(temp.mean, na.rm = TRUE),   
    tmin   = mean(temp.min, na.rm = TRUE),   
    .groups = "drop"
  )

counts_genit<- counts_genit%>% 
  mutate(holiday = if_else(dateonly %in% holiday_dates, 1, 0))

counts_genit_cts <- counts_genit %>%
  mutate(strata = factor(glue("{year(dateonly)}:{month(dateonly)}:{wday(dateonly)}")))


run_cts(data=counts_genit_cts,
         temp=counts_genit_cts$tmean,
         knots=c(0.33,0.66)) 

run_cts(data=counts_genit_cts,
         temp=counts_genit_cts$tmean,
         knots=c(0.50,0.90)) 

run_cts(data=counts_genit_cts,
         temp=counts_genit_cts$tmean,
         knots=c(0.10,0.75)) 

run_cts(data=counts_genit_cts,
        temp=counts_genit_cts$tmean,
        knots=c(0.25,0.50,0.75)) 


```

#### knots at (0.50,0.90) has the lowest AIC


```{r}

```
